version: '3'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrongPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
  
  taskmanagement:
    build: 
      context: ./TaskManagementSystem/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=TaskManagementSystem;User=sa;Password=YourStrongPassword123!;Encrypt=False;
      - EmailSettings__SmtpServer=smtp.mailtrap.io
      - EmailSettings__SmtpPort=2525
      - EmailSettings__SmtpUsername=your_mailtrap_username
      - EmailSettings__SmtpPassword=your_mailtrap_password
      - EmailSettings__SenderEmail=noreply@taskmanagementsystem.com
      - EmailSettings__SenderName=Task Management System
      - GoogleAuth__ClientId=your_google_client_id
      - GoogleAuth__ClientSecret=your_google_client_secret

volumes:
  sqlserver_data: 