# Gmail SMTP Configuration Example
# Note: You'll need to create an "App Password" in your Google account:
# https://myaccount.google.com/apppasswords

# Email settings for docker-compose.yml:
- EmailSettings__SmtpServer=smtp.gmail.com
- EmailSettings__SmtpPort=587
- EmailSettings__SmtpUsername=your.email@gmail.com
- EmailSettings__SmtpPassword=your-16-char-app-password
- EmailSettings__SenderEmail=your.email@gmail.com
- EmailSettings__SenderName=Task Management System
- EmailSettings__EnableSsl=true

# Instructions:
# 1. You must enable 2-Step Verification on your Google account
# 2. Create an App Password at https://myaccount.google.com/apppasswords
# 3. Use that App Password in the configuration above
# 4. There are sending limits with Gmail - not recommended for production use
# 5. Google may still block "less secure apps" - SendGrid is preferred 